"""Build notebooks/analysis.ipynb programmatically.

Run from the project root:
    python build_notebook.py

The notebook walks through Phases 1-3 end to end with plots and
explanatory markdown. Cells are pre-written so a reviewer can read
the analysis.ipynb without executing it -- but every cell will run
cleanly on a freshly-installed environment.
"""
import json
from pathlib import Path

NOTEBOOK_PATH = Path("notebooks/analysis.ipynb")


_counter = {"i": 0}


def _next() -> int:
    _counter["i"] += 1
    return _counter["i"]


def md(*lines: str) -> dict:
    return {
        "cell_type": "markdown",
        "id": f"cell-{_next():02d}",
        "metadata": {},
        "source": [l + "\n" for l in lines[:-1]] + [lines[-1]],
    }


def code(*lines: str) -> dict:
    return {
        "cell_type": "code",
        "id": f"cell-{_next():02d}",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [l + "\n" for l in lines[:-1]] + [lines[-1]],
    }


cells = [
    md(
        "# SECOM SPC + FDC — Analysis Notebook",
        "",
        "**Yeshudan Bora · CMU MS AI Engineering — Chemical Engineering**",
        "",
        "This notebook walks through the full Statistical Process Control + ",
        "Multivariate Fault Detection pipeline on the SECOM dataset, end to ",
        "end. Each section corresponds to one phase of the project:",
        "",
        "1. **Phase 1** — Data ingestion, cleaning, critical-sensor selection",
        "2. **Phase 2** — Univariate SPC: I-MR charts, Nelson rules, Cp/Cpk",
        "3. **Phase 3** — Multivariate FDC: PCA T² + SPE/Q + contribution analysis",
        "",
        "Run the cells top-to-bottom. The notebook reads from `data/raw/` and ",
        "writes intermediate artefacts to `data/processed/`.",
    ),
    md(
        "## 0. Imports & setup",
    ),
    code(
        "import sys",
        "from pathlib import Path",
        "",
        "# Add project root to path so we can import src/ when running from notebooks/",
        "ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()",
        "sys.path.insert(0, str(ROOT))",
        "",
        "import numpy as np",
        "import pandas as pd",
        "import matplotlib.pyplot as plt",
        "",
        "plt.rcParams['figure.figsize'] = (10, 5)",
        "plt.rcParams['axes.grid'] = True",
        "plt.rcParams['grid.alpha'] = 0.3",
        "",
        "RAW = ROOT / 'data' / 'raw'",
        "OUT = ROOT / 'data' / 'processed'",
        "OUT.mkdir(parents=True, exist_ok=True)",
        "print('Project root:', ROOT)",
    ),
    md(
        "## Phase 1 — Data ingestion & cleaning",
        "",
        "The SECOM dataset has 1,567 wafer runs × 590 sensors, with NaN-encoded ",
        "missing values and a binary pass/fail label. The cleaning pipeline:",
        "",
        "1. **Drop sensors with > 50% missing** — broken/offline equipment.",
        "2. **Drop zero-variance sensors** — constants carry no SPC information.",
        "3. **Drop highly correlated sensors (|ρ| > 0.99)** — redundant taps.",
        "4. **Median-impute residual NaNs** in the surviving sensors.",
        "",
        "Each threshold corresponds to a real engineering decision and is documented ",
        "in `src/data_loader.py`'s `CleaningConfig` dataclass.",
    ),
    code(
        "from src.data_loader import load_raw, clean, select_critical_sensors",
        "",
        "df = load_raw(RAW / 'secom.data', RAW / 'secom_labels.data')",
        "print(f'Raw shape: {df.shape}')",
        "print(f'Pass / fail counts: {(~df.is_fail).sum()} / {df.is_fail.sum()}')",
        "df.head()",
    ),
    code(
        "cleaned, report = clean(df)",
        "print(report.summary())",
    ),
    code(
        "cleaned.to_parquet(OUT / 'secom_clean.parquet', index=False)",
        "(OUT / 'cleaning_report.txt').write_text(report.summary())",
        "print(f\"Wrote {OUT / 'secom_clean.parquet'} ({cleaned.shape[0]} rows × {cleaned.shape[1]} cols)\")",
    ),
    md(
        "### Critical-sensor selection",
        "",
        "We rank sensors by absolute Pearson correlation with the fail label and ",
        "keep the top 25. This is supervised feature selection — it uses outcome ",
        "data to decide *what to monitor*, but the FDC model in Phase 3 is then ",
        "fit on a pass-only baseline, so the model itself never sees a failure ",
        "during training. See `reports/methodology_sensor_selection.md` for the ",
        "full discussion and the variance-based robustness check.",
    ),
    code(
        "critical = select_critical_sensors(cleaned, n=25, method='fail_corr')",
        "(OUT / 'critical_sensors.txt').write_text('\\n'.join(critical))",
        "print('Top 25 critical sensors:')",
        "for i, s in enumerate(critical, 1):",
        "    print(f'  {i:2d}. {s}')",
    ),
    md(
        "## Phase 2 — Univariate SPC",
        "",
        "**Baseline split:** first 70% of pass-only wafers (chronologically) form ",
        "the in-control reference. The remaining 30% pass + all 104 fails form the ",
        "monitoring set on which Nelson rules are evaluated. This prevents control ",
        "limits from \"seeing\" the excursions they are supposed to detect.",
        "",
        "**Sigma estimates:**",
        "- σ_within = MR̄ / d₂ (d₂ = 1.128 for n=2 moving ranges) — used for ",
        "  control limits and Cp/Cpk denominators",
        "- σ_overall = std(baseline) — used to set USL / LSL = μ ± 3σ_overall",
        "",
        "When σ_within < σ_overall, the process drifts more than its inherent ",
        "noise, and Cp > 1 reflects the gap.",
    ),
    code(
        "from src.spc import (",
        "    split_baseline_monitoring, fit_control_limits, nelson_rules, run_univariate_spc,",
        ")",
        "",
        "baseline, monitoring = split_baseline_monitoring(cleaned, baseline_frac=0.70)",
        "print(f'Baseline (in-control)  : {len(baseline):>4} wafers, {baseline.is_fail.sum()} fails')",
        "print(f'Monitoring (held-out)  : {len(monitoring):>4} wafers, {monitoring.is_fail.sum()} fails')",
    ),
    code(
        "summary, limits_by, rules_by = run_univariate_spc(cleaned, critical)",
        "summary.to_csv(OUT / 'spc_summary.csv', index=False)",
        "summary[['sensor', 'mu', 'mu_monitoring', 'mean_shift_sigma',",
        "         'sigma_within', 'sigma_overall', 'drift_ratio',",
        "         'Cp', 'Cpk_baseline', 'Cpk_monitoring',",
        "         'flagged_points', 'flag_rate']].round(3).head(10)",
    ),
    md(
        "### Cpk leaderboard",
        "",
        "Sorting by `Cpk_monitoring` ascending shows which sensors have lost ",
        "capability during the monitoring window. Anything below 1.0 is no longer ",
        "meeting its natural ±3σ tolerance.",
    ),
    code(
        "ax = summary.set_index('sensor')[['Cpk_baseline', 'Cpk_monitoring']].plot.barh(",
        "    figsize=(10, 8), color=['steelblue', 'crimson'])",
        "ax.axvline(1.0, color='black', linestyle='--', label='Cpk = 1.0 threshold')",
        "ax.set_xlabel('Cpk')",
        "ax.set_title('Cpk: baseline (training) vs monitoring (held-out)')",
        "ax.legend()",
        "plt.tight_layout()",
        "plt.show()",
    ),
    md(
        "### Example I-MR chart",
        "",
        "Pick the worst-Cpk sensor on the monitoring set and plot its Individuals ",
        "chart with control limits, zone bands, and Nelson-rule violations.",
    ),
    code(
        "worst_sensor = summary.iloc[0]['sensor']",
        "lim = limits_by[worst_sensor]",
        "rules = rules_by[worst_sensor]",
        "values = monitoring[worst_sensor].to_numpy()",
        "violations = rules.any_violation()",
        "",
        "fig, ax = plt.subplots(figsize=(12, 5))",
        "x = np.arange(len(values))",
        "ax.plot(x, values, color='steelblue', linewidth=0.9, marker='.', markersize=3)",
        "ax.axhline(lim.mu,    color='black',    linewidth=1.2, label=f'μ = {lim.mu:.3f}')",
        "ax.axhline(lim.ucl_i, color='crimson',  linestyle='--', label=f'UCL = {lim.ucl_i:.3f}')",
        "ax.axhline(lim.lcl_i, color='crimson',  linestyle='--', label=f'LCL = {lim.lcl_i:.3f}')",
        "ax.axhline(lim.zone_a_upper, color='orange', linestyle=':', alpha=0.6)",
        "ax.axhline(lim.zone_a_lower, color='orange', linestyle=':', alpha=0.6)",
        "ax.scatter(x[violations], values[violations], color='red', zorder=5,",
        "           label=f'Nelson violations ({violations.sum()})')",
        "ax.set_title(f'I-chart — {worst_sensor}  (Cpk_monitoring = {summary.iloc[0][\"Cpk_monitoring\"]:.2f})')",
        "ax.set_xlabel('Wafer index (monitoring set)')",
        "ax.set_ylabel(worst_sensor)",
        "ax.legend(loc='upper right', fontsize=9)",
        "plt.tight_layout()",
        "plt.show()",
    ),
    md(
        "### Nelson rule violation breakdown",
        "",
        "Aggregating the violation counts across all monitored sensors shows ",
        "*which* failure patterns are most common in this fab. In SECOM the ",
        "dominant patterns are Rule 5 (2-of-3 in zone A) and Rule 6 (4-of-5 in ",
        "zone B) — both signal a meaningful drift in the process mean rather ",
        "than isolated outliers.",
    ),
    code(
        "rule_cols = [f'rule_{i}' for i in range(1, 9)]",
        "totals = summary[rule_cols].sum().sort_values(ascending=False)",
        "ax = totals.plot.bar(figsize=(8, 4), color='steelblue', edgecolor='black')",
        "ax.set_xlabel('Nelson rule')",
        "ax.set_ylabel('Total violations across 25 monitored sensors')",
        "ax.set_title('Nelson rule violation counts (monitoring set)')",
        "for i, v in enumerate(totals):",
        "    ax.text(i, v, f'{int(v)}', ha='center', va='bottom', fontsize=9)",
        "plt.tight_layout()",
        "plt.show()",
    ),
    md(
        "## Phase 3 — Multivariate FDC (PCA T² + SPE/Q)",
        "",
        "Univariate SPC misses correlated excursions: wafers where every sensor ",
        "stays within its own ±3σ band but the *joint* state has wandered out of ",
        "the operating envelope. PCA-based FDC catches these with two ",
        "complementary statistics:",
        "",
        "- **Hotelling's T²** — distance from the origin *inside* the K-component ",
        "  model subspace, normalized by each PC's variance. Catches deviations ",
        "  along known correlation directions.",
        "- **SPE / Q** — squared residual *orthogonal* to the model subspace. ",
        "  Catches wafers whose correlation structure breaks down — sensors that ",
        "  normally move together suddenly don't.",
        "",
        "**Control limits at α = 0.01 (99% confidence):**",
        "- T² limit: scaled F-distribution closed form",
        "- SPE limit: Jackson-Mudholkar (1979) closed form",
    ),
    code(
        "from src.fdc import (",
        "    fit_pca, score, t2_contributions, spe_contributions,",
        "    evaluate_against_labels,",
        ")",
        "",
        "model = fit_pca(baseline, critical, var_threshold=0.90, alpha=0.01)",
        "print(f'PCA model fitted on {model.N_baseline} in-control wafers, '",
        "      f'{len(model.sensor_cols)} sensors')",
        "print(f'Components retained (K) : {model.K} (>= 90% variance)')",
        "print(f'Variance explained      : '",
        "      f'{model.explained_variance_ratio[:model.K].sum():.3f}')",
        "print(f'T^2 limit (99%)         : {model.t2_limit:.3f}')",
        "print(f'SPE limit (99%)         : {model.spe_limit:.3f}')",
    ),
    md(
        "### Scree plot",
        "",
        "Cumulative variance vs number of components. The vertical line marks ",
        "the cutoff at K = 12; the horizontal line marks the 90% threshold.",
    ),
    code(
        "evr = model.explained_variance_ratio",
        "cum = np.cumsum(evr)",
        "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))",
        "ax1.bar(range(1, len(evr) + 1), evr, color='steelblue', edgecolor='black')",
        "ax1.set_xlabel('Component')",
        "ax1.set_ylabel('Variance explained')",
        "ax1.set_title('Per-component variance')",
        "ax2.plot(range(1, len(cum) + 1), cum, marker='o', color='crimson')",
        "ax2.axhline(0.90, color='black', linestyle='--', label='90% threshold')",
        "ax2.axvline(model.K, color='gray', linestyle=':', label=f'K = {model.K}')",
        "ax2.set_xlabel('Number of components')",
        "ax2.set_ylabel('Cumulative variance explained')",
        "ax2.set_title('Cumulative variance')",
        "ax2.legend()",
        "plt.tight_layout()",
        "plt.show()",
    ),
    md(
        "### T² and SPE control charts",
        "",
        "Score every wafer in the monitoring set, plot T² and SPE side-by-side ",
        "with their 99% limits. Real fail wafers are shown in red. The mix of ",
        "T²-only / SPE-only / both alarms is itself diagnostic — different ",
        "alarm types correspond to different excursion modes.",
    ),
    code(
        "scores = score(model, monitoring)",
        "is_fail = monitoring['is_fail'].to_numpy()",
        "x = np.arange(len(monitoring))",
        "",
        "fig, axes = plt.subplots(2, 1, figsize=(13, 7), sharex=True)",
        "for ax, stat, limit, name in zip(",
        "    axes,",
        "    [scores.t2, scores.spe],",
        "    [scores.t2_limit, scores.spe_limit],",
        "    ['Hotelling T²', 'SPE / Q'],",
        "):",
        "    ax.plot(x, stat, color='steelblue', linewidth=0.7, alpha=0.7)",
        "    ax.axhline(limit, color='black', linestyle='--', label=f'99% limit = {limit:.2f}')",
        "    above = stat > limit",
        "    ax.scatter(x[above & ~is_fail], stat[above & ~is_fail], color='orange', s=18, label='False alarm', zorder=4)",
        "    ax.scatter(x[above &  is_fail], stat[above &  is_fail], color='red',    s=24, label='True positive (fail wafer)', zorder=5)",
        "    ax.scatter(x[~above & is_fail], stat[~above & is_fail], color='gray',   s=14, alpha=0.6, label='Missed fail', zorder=3)",
        "    ax.set_ylabel(name)",
        "    ax.set_yscale('log')",
        "    ax.legend(loc='upper right', fontsize=9)",
        "axes[-1].set_xlabel('Monitoring wafer index')",
        "axes[0].set_title('Multivariate FDC control charts (99% confidence)')",
        "plt.tight_layout()",
        "plt.show()",
    ),
    md(
        "### Detection scorecard",
        "",
        "Treat fail wafers as positives and the alarm flag (T² OR SPE above limit) ",
        "as the predictor. The headline number is **precision** — when the system ",
        "raises an alarm, how often is it right? Compare against the base-rate ",
        "fail probability (104 / 543 ≈ 19.2%).",
    ),
    code(
        "metrics = evaluate_against_labels(scores, is_fail)",
        "print('Confusion matrix on monitoring set:')",
        "print(f'  TP : {metrics[\"TP\"]:>4}    FP : {metrics[\"FP\"]:>4}')",
        "print(f'  FN : {metrics[\"FN\"]:>4}    TN : {metrics[\"TN\"]:>4}')",
        "print()",
        "print(f'  Recall (TPR)        : {metrics[\"TPR (recall)\"]:.3f}')",
        "print(f'  False alarm rate    : {metrics[\"FPR (false alarm)\"]:.3f}')",
        "print(f'  Precision           : {metrics[\"precision\"]:.3f}')",
        "print(f'  F1                  : {metrics[\"F1\"]:.3f}')",
        "base_rate = is_fail.mean()",
        "print(f'  Base-rate fail prob : {base_rate:.3f}')",
        "print(f'  Precision lift      : {metrics[\"precision\"] / base_rate:.2f}×')",
        "print()",
        "print(f'  T^2-only alarms     : {metrics[\"t2_only_alarms\"]}')",
        "print(f'  SPE-only alarms     : {metrics[\"spe_only_alarms\"]}')",
        "print(f'  Both-stat alarms    : {metrics[\"both_alarms\"]}')",
    ),
    md(
        "### Root-cause: contribution analysis on the worst alarm",
        "",
        "When a wafer trips the limit, decompose T² and SPE into per-sensor ",
        "contributions. The MacGregor decomposition gives:",
        "",
        "$$ \\text{contrib}_j (T^2) = \\sum_{k=1}^K \\frac{P_{jk} \\, x_j \\, t_k}{\\lambda_k} \\quad,\\quad \\text{contrib}_j(\\text{SPE}) = (x_j - \\hat{x}_j)^2 $$",
        "",
        "and the contributions sum exactly to the parent statistic — verified in ",
        "`tests/test_fdc.py`. The top-N contributors are the sensor(s) the ",
        "process engineer should look at first.",
    ),
    code(
        "worst_idx = int(np.argmax(scores.t2))",
        "wafer = monitoring.iloc[worst_idx]",
        "ct2 = t2_contributions(model, wafer)",
        "cspe = spe_contributions(model, wafer)",
        "",
        "print(f'Worst T^2 wafer       : monitoring index {worst_idx}, '",
        "      f'timestamp {wafer[\"timestamp\"]}')",
        "print(f'  T^2 = {scores.t2[worst_idx]:.2f} (limit {model.t2_limit:.2f})')",
        "print(f'  SPE = {scores.spe[worst_idx]:.2f} (limit {model.spe_limit:.2f})')",
        "print(f'  Actual outcome    : '",
        "      f'{\"FAIL\" if wafer[\"is_fail\"] else \"pass\"}')",
        "",
        "fig, axes = plt.subplots(1, 2, figsize=(13, 4))",
        "ct2.head(10).plot.barh(ax=axes[0], color='crimson')",
        "axes[0].set_title('Top 10 T² contributors')",
        "axes[0].invert_yaxis()",
        "axes[0].set_xlabel('Contribution to T²')",
        "cspe.head(10).plot.barh(ax=axes[1], color='steelblue')",
        "axes[1].set_title('Top 10 SPE contributors')",
        "axes[1].invert_yaxis()",
        "axes[1].set_xlabel('Contribution to SPE')",
        "plt.tight_layout()",
        "plt.show()",
    ),
    md(
        "### Methodology robustness check",
        "",
        "Re-run the entire FDC pipeline using **variance-only** (unsupervised) ",
        "sensor selection. The two methods share only 2 of 25 sensors. The ",
        "supervised run dominates — fail-correlated sensors carry the most ",
        "signal — but the unsupervised run is fully leakage-free. Both numbers ",
        "are documented in `reports/methodology_sensor_selection.md`.",
    ),
    code(
        "from src.fdc import run_fdc",
        "",
        "crit_var = select_critical_sensors(cleaned, n=25, method='variance')",
        "_, _, scores_var, m_var = run_fdc(cleaned, crit_var)",
        "_, _, _, m_corr = run_fdc(cleaned, critical)",
        "",
        "comparison = pd.DataFrame({",
        "    'fail_corr (headline)': {",
        "        'TPR': m_corr['TPR (recall)'],",
        "        'FPR': m_corr['FPR (false alarm)'],",
        "        'Precision': m_corr['precision'],",
        "        'F1': m_corr['F1'],",
        "    },",
        "    'variance (robustness)': {",
        "        'TPR': m_var['TPR (recall)'],",
        "        'FPR': m_var['FPR (false alarm)'],",
        "        'Precision': m_var['precision'],",
        "        'F1': m_var['F1'],",
        "    },",
        "}).T.round(3)",
        "comparison",
    ),
    md(
        "## Summary",
        "",
        "| Phase | Output |",
        "| --- | --- |",
        "| Phase 1 | 590 → 351 sensors after cleaning, 25 selected for monitoring |",
        "| Phase 2 | I-MR + Nelson + Cp/Cpk; 2 sensors with Cpk_monitoring < 1.0 |",
        "| Phase 3 | PCA T² + SPE; **56% precision @ 3.9% FPR (2.95× base-rate lift)** |",
        "| Phase 4 | Alarm catalog + Pareto contributions + 'usual suspect' leaderboard |",
        "| Phase 5 | EWMA R2R controller; 50–65% of Nelson violations prevented |",
        "| Phase 6 | PostgreSQL schema + SparkSQL ingest; SQL-sourced pipeline matches file-sourced bit-for-bit |",
        "",
        "The full module-level details are in `src/`, every module has unit ",
        "tests in `tests/` (30 tests, all passing — 26 if Postgres is not ",
        "available), the methodology discussion is in ",
        "`reports/methodology_sensor_selection.md`, and the SQL/Spark ",
        "architecture is documented in `reports/sql_data_layer.md`.",
    ),
]


notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.10",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}


NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
NOTEBOOK_PATH.write_text(json.dumps(notebook, indent=1))
print(f"Wrote {NOTEBOOK_PATH} ({len(cells)} cells)")
